export const ACTIONS = {
  PANEL_STATE_CHANGED: 'ANTIGRAVITY_PANEL_STATE_CHANGED',
  PANEL_WIDTH_CHANGED: 'ANTIGRAVITY_PANEL_WIDTH_CHANGED',
  INSPECT_MODE_CHANGED: 'ANTIGRAVITY_INSPECT_MODE_CHANGED',
  PING: 'ANTIGRAVITY_PING',
  SELECTION_CHANGED: 'ANTIGRAVITY_SELECTION_CHANGED',
  SPACING_CHANGED: 'ANTIGRAVITY_SPACING_CHANGED',
  STYLE_CHANGED: 'ANTIGRAVITY_STYLE_CHANGED',
  TAG_CHANGED: 'ANTIGRAVITY_TAG_CHANGED',
  RESET_SPACING: 'ANTIGRAVITY_RESET_SPACING',
};

export const DEFAULT_PANEL_WIDTH = 360;
